#!/usr/bin/env python3
"""Parse Kotlin compiler logs and generate normalized error summaries."""

from __future__ import annotations

import argparse
import csv
import os
import re
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

LINE_PATTERNS = [
    re.compile(r"^\s*e:\s+(.+?):\s*\((\d+),\s*\d+\):\s*(.+)$"),
    re.compile(r"^\s*(.+\.kt):([0-9]+):[0-9]+:\s+error:\s+(.+)$"),
    re.compile(r"^\s*error:\s+(.+)$"),
]
CODE_PATTERN = re.compile(r"\[([A-Z0-9_]+)]")


@dataclass(frozen=True)
class ErrorRecord:
    source_set: str
    task: str
    error_code: str
    message: str
    file: str
    line: str


def _extract_error(line: str, source_set: str, task: str) -> ErrorRecord | None:
    match = LINE_PATTERNS[0].match(line)
    if match:
        file_path, line_no, message = match.groups()
        code_match = CODE_PATTERN.search(message)
        error_code = code_match.group(1) if code_match else "KOTLIN_COMPILE_ERROR"
        return ErrorRecord(source_set, task, error_code, message.strip(), file_path.strip(), line_no)

    match = LINE_PATTERNS[1].match(line)
    if match:
        file_path, line_no, message = match.groups()
        code_match = CODE_PATTERN.search(message)
        error_code = code_match.group(1) if code_match else "KOTLIN_COMPILE_ERROR"
        return ErrorRecord(source_set, task, error_code, message.strip(), file_path.strip(), line_no)

    match = LINE_PATTERNS[2].match(line)
    if match:
        message = match.group(1).strip()
        code_match = CODE_PATTERN.search(message)
        error_code = code_match.group(1) if code_match else "KOTLIN_COMPILE_ERROR"
        return ErrorRecord(source_set, task, error_code, message, "<unknown>", "0")

    return None


def parse_logs(log_paths: Iterable[Path]) -> list[ErrorRecord]:
    records: list[ErrorRecord] = []
    for path in log_paths:
        source_set = path.stem
        task = path.name.replace(".log", "")
        try:
            content = path.read_text(encoding="utf-8", errors="replace").splitlines()
        except FileNotFoundError:
            continue

        for line in content:
            record = _extract_error(line, source_set=source_set, task=task)
            if record:
                records.append(record)

    return records


def write_summary(records: list[ErrorRecord], output_tsv: Path) -> None:
    output_tsv.parent.mkdir(parents=True, exist_ok=True)
    counts = Counter(records)

    ordered = sorted(
        counts.items(),
        key=lambda item: (
            item[0].source_set,
            item[0].task,
            item[0].error_code,
            item[0].message,
            item[0].file,
            int(item[0].line) if item[0].line.isdigit() else item[0].line,
        ),
    )

    with output_tsv.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.writer(fh, delimiter="\t")
        writer.writerow(["source_set", "task", "error_code", "message", "file", "line", "count"])
        for record, count in ordered:
            writer.writerow([
                record.source_set,
                record.task,
                record.error_code,
                record.message,
                record.file,
                record.line,
                str(count),
            ])


def write_tracker(
    records: list[ErrorRecord],
    tracker_path: Path,
    github_repository: str,
) -> None:
    repository = github_repository or "owner/repo"
    label_by_source_set = {
        "compileDebugKotlin": "kotlin-compile",
        "compileDebugUnitTestKotlin": "kotlin-test",
        "compileDebugAndroidTestKotlin": "kotlin-androidTest",
    }

    unique: dict[tuple[str, str], set[str]] = defaultdict(set)
    examples: dict[tuple[str, str], ErrorRecord] = {}

    for record in records:
        label = label_by_source_set.get(record.task, "kotlin-compile")
        key = (label, record.message)
        unique[key].add(record.error_code)
        examples[key] = record

    rows = sorted(unique.keys(), key=lambda k: (k[0], k[1]))

    lines = [
        "# Kotlin Compiler Error Baseline",
        "",
        "This document is generated by CI from Kotlin compile logs.",
        "It tracks unique compiler errors so pull requests can show net reduction over time.",
        "",
        "| Label | Error Code(s) | Message | Example Location | Issue Queue |",
        "|---|---|---|---|---|",
    ]

    if not rows:
        lines.append("| _(none)_ | - | No Kotlin compile errors detected. | - | - |")
    else:
        for label, message in rows:
            codes = ", ".join(sorted(unique[(label, message)]))
            example = examples[(label, message)]
            location = f"`{example.file}:{example.line}`"
            label_query = (
                f"https://github.com/{repository}/issues"
                f"?q=is%3Aissue+is%3Aopen+label%3A{label}"
            )
            message_cell = message.replace("|", "\\|")
            lines.append(
                f"| `{label}` | `{codes}` | {message_cell} | {location} | "
                f"[open {label} issues]({label_query}) |"
            )

    lines.extend(
        [
            "",
            "## Source files",
            "",
            "- `artifacts/kotlin-compile/normalized-summary.tsv`: normalized error inventory used by CI artifacts.",
            "- `artifacts/kotlin-compile/raw/*.log`: full compiler task logs.",
        ]
    )

    tracker_path.parent.mkdir(parents=True, exist_ok=True)
    tracker_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Kotlin compile error inventory.")
    parser.add_argument("--logs-dir", required=True, help="Directory with Kotlin task log files.")
    parser.add_argument("--summary-tsv", required=True, help="Path to write normalized summary TSV.")
    parser.add_argument(
        "--tracker-md",
        required=True,
        help="Path to write markdown tracker with unique error baselines.",
    )
    parser.add_argument(
        "--github-repository",
        default=os.environ.get("GITHUB_REPOSITORY", ""),
        help="owner/repo used for issue label links.",
    )
    args = parser.parse_args()

    logs_dir = Path(args.logs_dir)
    log_paths = sorted(logs_dir.glob("*.log"))
    records = parse_logs(log_paths)

    write_summary(records, Path(args.summary_tsv))
    write_tracker(records, Path(args.tracker_md), args.github_repository or "")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
